using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using SsisLineage.Core.Models;

namespace SsisLineage.Core
{
    public static class ProjectExportService
    {
        public static byte[] ExportToTemplateZip(LineageGraph graph, string templateZipPath)
        {
            // 1. Generate all codes for the project
            var dbtResult = SsisMigrationConverter.ConvertProject(graph, MigrationTarget.DbtSql);
            var pandasResult = SsisMigrationConverter.ConvertProject(graph, MigrationTarget.PythonPandas);
            var airflowResult = SsisMigrationConverter.ConvertProject(graph, MigrationTarget.AirflowDag);

            using var ms = new MemoryStream();

            // 2. Load the base template zip if it exists
            if (File.Exists(templateZipPath))
            {
                var templateBytes = File.ReadAllBytes(templateZipPath);
                ms.Write(templateBytes, 0, templateBytes.Length);
            }
            else
            {
                // Fallback to empty zip if template not found
                using (var emptyArchive = new ZipArchive(ms, ZipArchiveMode.Create, true)) { }
            }

            ms.Position = 0;

            // 3. Inject our generated files into the appropriate folders
            using (var archive = new ZipArchive(ms, ZipArchiveMode.Update, true))
            {
                // Add Airflow DAGs to dags/
                foreach (var file in airflowResult.Files)
                {
                    AddOrReplaceEntry(archive, $"dags/{file.FileName}", file.Content);
                }

                // Add Python Pandas Extract Scripts to dags/scripts/ (as per Joseph's template style, or a new src/ folder)
                foreach (var file in pandasResult.Files)
                {
                    AddOrReplaceEntry(archive, $"dags/scripts/{file.FileName}", file.Content);
                }

                // Add dbt models to dags/dbt_project/models/
                foreach (var file in dbtResult.Files)
                {
                    AddOrReplaceEntry(archive, $"dags/dbt_project/models/{file.FileName}", file.Content);
                }

                // Add a custom README explaining the migration
                var readmeContent = 
@"# SSIS Migrated Modern Data Engineering Project

This project was automatically generated by **SSIS Lineage Hub** based on the [Joseph Machado's Data Engineering Template](https://github.com/josephmachado/data_engineering_project_template).

## Migration Artifacts
- **Airflow DAGs (`dags/`)**: Auto-generated control flow orchestration converted from SSIS packages.
- **Python Scripts (`dags/scripts/`)**: Pandas and pyodbc-based scripts for extracting data from OLE DB to local Landing Zone (Parquet).
- **dbt Models (`dags/dbt_project/models/`)**: SQL transformations mapped from SSIS Data Flow components (Derived Column, Lookup, etc.).

## Next Steps
1. Run `make up` to start the infrastructure (Airflow, Postgres/SQLServer).
2. Configure your dbt profiles and Airflow connections.
3. Review the generated Airflow DAGs and dbt models for accuracy against legacy SSIS.
";
                AddOrReplaceEntry(archive, "MIGRATION_README.md", readmeContent);

                // Feature 1: Connection & Variable Mapper (.env generation)
                var envContent = new System.Text.StringBuilder();
                envContent.AppendLine("# Auto-generated Environment Variables from SSIS Connection Managers");
                envContent.AppendLine("AIRFLOW_CONN_SQLSERVER_DEFAULT=mssql+pyodbc://sa:YourPassword123!@localhost:1433/SsisDemoDB?driver=ODBC+Driver+17+for+SQL+Server");
                envContent.AppendLine("DBT_PROFILES_DIR=./dbt_project");
                
                var connections = new HashSet<string>();
                foreach (var pkg in graph.Packages)
                {
                    foreach (var conn in pkg.ConnectionManagers)
                    {
                        if (connections.Add(conn))
                        {
                            var cleanName = System.Text.RegularExpressions.Regex.Replace(conn, @"[^\w]", "_").ToUpperInvariant();
                            envContent.AppendLine($"AIRFLOW_CONN_SSIS_{cleanName}=mssql+pyodbc://user:pass@host/db");
                        }
                    }
                }
                AddOrReplaceEntry(archive, ".env", envContent.ToString());

                // Feature 3: GitHub Actions CI/CD Export
                var githubActionsContent = 
@"name: Modern Data Stack CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r containers/airflow/requirements.txt
          pip install pytest

      - name: Run Airflow DAG Tests
        run: |
          pytest tests/dags/

      - name: Run dbt Tests (Dry Run)
        run: |
          echo ""Mocking dbt test execution...""
          # cd dbt_project && dbt deps && dbt test --target dev
";
                AddOrReplaceEntry(archive, ".github/workflows/ci-cd.yml", githubActionsContent);
            }

            return ms.ToArray();
        }

        private static void AddOrReplaceEntry(ZipArchive archive, string entryName, string content)
        {
            var existingEntry = archive.GetEntry(entryName);
            if (existingEntry != null)
            {
                existingEntry.Delete();
            }

            var entry = archive.CreateEntry(entryName, CompressionLevel.Optimal);
            using var entryStream = entry.Open();
            using var writer = new StreamWriter(entryStream);
            writer.Write(content);
        }
    }
}
